### ISSUE TITLE
JSMpeg takes data as "garbage" with audio

### ISSUE THREAD

**Issue by jeda** [crybapp/web#36]
```
vendors.app.js:606 warn JSMpeg: Possible garbage data. Skipping.
value @ vendors.app.js:606
vendors.app.js:606 warn JSMpeg: Possible garbage data. Skipping.
value @ vendors.app.js:606
wasm-0002793e:22 Uncaught RuntimeError: memory access out of bounds
    at wasm-function[21]:0x121f
    at wasm-function[20]:0xee4
    at wasm-function[19]:0xdbb
    at wasm-function[18]:0xccb
    at MPEG1WASM.decode (https://cryb.app/js/jsmpeg.min.js:3:20525)
    at Player.updateForStreaming (https://cryb.app/js/jsmpeg.min.js:1:8886)
    at Player.update (https://cryb.app/js/jsmpeg.min.js:1:8758)
```

Pretty much of this - and might be the cause of audio choking.

**Comment by MinkiNTN** [comment]
I have done some testing, and found something quite odd: The same Cryb repos running on Windows, give a lot of garbage data warnings with choppy audio, while the one running on Linux (Ubuntu) is streaming flawlessly on the host PC, and slightly choppy but not garbage data on a remote client.

**Comment by jeda** [comment]
This got fixed. Closing!
